const { tokens, depthScale } = require('./tokens');

const HEX = /^#[0-9a-fA-F]{6}$/;

/** Guards against a malformed token reaching the stylesheet. Returns the colour unchanged. */
function assertHexColor(hex) {
  if (typeof hex !== 'string' || !HEX.test(hex)) {
    throw new TypeError(`assertHexColor: expected a six-digit hex colour, got ${hex}`);
  }
  return hex;
}

const CAMEL_TO_KEBAB = /[A-Z]/g;

function varsFor(scheme, indent) {
  const lines = [];
  for (const [name, hex] of Object.entries(tokens[scheme])) {
    const kebab = name.replace(CAMEL_TO_KEBAB, (c) => `-${c.toLowerCase()}`);
    lines.push(`${indent}--color-${kebab}: ${assertHexColor(hex)};`);
  }
  depthScale[scheme].forEach((hex, i) => {
    lines.push(`${indent}--color-depth-${i + 1}: ${assertHexColor(hex)};`);
  });
  return lines.join('\n');
}

/**
 * The whole of global.css, derived from tokens.js. Never hand-edit global.css.
 *
 * Tailwind v4 is CSS-first: the @theme block is what generates the utility
 * classes (--color-bg becomes bg-bg, --color-depth-3 becomes text-depth-3).
 * Redefining the same custom properties under prefers-color-scheme is the
 * whole of theme switching — NativeWind maps that media query to React
 * Native's Appearance API, so no provider or JS is involved.
 */
function buildThemeCss() {
  return `/* GENERATED by scripts/build-theme-css.mjs from src/theme/tokens.js — do not edit. */
@import "tailwindcss";
@import "nativewind/theme";

@theme {
${varsFor('light', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root {
${varsFor('dark', '    ')}
  }
}
`;
}

module.exports = { assertHexColor, buildThemeCss };
