import path from 'node:path';

import sharp from 'sharp';

// **The one graphic Ponor ships, checked as a graphic** (DESIGN.md §0.1/§0.3, M1h).
//
// It lives beside the theme because what it pins is a claim about COLOUR, and colour is this
// directory's subject: `assets/images/mark-mono.png` is the mark `EmptyState` draws at 120 pt,
// and the whole reason it exists as a separate asset from `icon.png` is that the on-screen mark
// may not carry the depth gradient. §0.3 strokes that gradient on the icon, where the mark is
// the only thing there is; inside the interface the same gradient is colour used as **brand**,
// and §0.1 says colour encodes depth and nothing else — on the one screen whose entire job is
// teaching that rule.
//
// **Why the artifact and not the script.** `scripts/build-icons.mjs` already refuses to build a
// mono mark that carries a second colour, and that guard is the fix; this is the proof it ran.
// The PNG is committed (Metro bundles it, so it has to be), `icons:build` is not part of any
// gate, and a mark regenerated by hand — or edited, or copied from `icon.png` because it looked
// close enough — would reach a diver with nothing in between. What is asserted is therefore the
// property, not the pipeline: **every pixel a diver can see is one colour.**
//
// A `tintColor` repaints exactly those pixels from the theme's ink (`emptyStateMark`,
// styles.ts), so the shipped white is what the tint replaces rather than what anybody sees.
// That is also why this test is worth more than it looks: a tint uses only the alpha channel on
// every platform we can check, so a gradient asset would render identically everywhere we would
// think to look and show its true colours only where tinting quietly does not apply.
const MARK = path.join(__dirname, '..', '..', 'assets', 'images', 'mark-mono.png');

describe('the mark the first-run screen draws', () => {
  it('carries exactly one colour, over a transparent ground', async () => {
    const { data, info } = await sharp(MARK).raw().toBuffer({ resolveWithObject: true });
    expect(info.channels).toBe(4);

    const inks = new Set<string>();
    let visible = 0;
    for (let i = 0; i < data.length; i += info.channels) {
      // Alpha 0 is the ground, and it is the whole of the image outside the drawing: an opaque
      // background would put a rectangle of ink behind the mark on both themes, one of which
      // would be invisible. Anti-aliased edges are partially transparent and still have to
      // agree on the colour, so they are counted rather than skipped.
      if (data[i + 3] === 0) continue;
      visible += 1;
      inks.add([data[i], data[i + 1], data[i + 2]].join(','));
    }

    // The drawing is actually there — an empty or fully transparent PNG would satisfy "one
    // colour" vacuously, and would render as a 120 pt hole above the label.
    expect(visible).toBeGreaterThan(1000);
    expect([...inks]).toEqual(['255,255,255']);
  });

  // **The wave stays behind the profile, and in a monochrome mark that has to be alpha.**
  // §0.3 puts it there on purpose ("chosen to sit quietly behind the profile") and uses
  // COLOUR to do it — a flat grey wave against a saturated gradient descent. Flatten both to
  // one ink at one width and they stop being two objects: the wave's ends curve down into the
  // profile's start, and the 120 pt render reads as a longhorn skull. Seen on the simulator,
  // which is the only place it could be seen.
  //
  // Pinned as two large populations rather than as an exact alpha, because the number is a
  // design judgement and the rule is the hierarchy. Anti-aliasing alone cannot satisfy it: an
  // opaque wave leaves only stroke edges near half alpha, a few hundred pixels at this size,
  // where a translucent one contributes the whole interior of a stroke running the full width
  // of the mark.
  it('keeps the wave translucent behind a solid profile, so the two read as two objects', async () => {
    const { data, info } = await sharp(MARK).raw().toBuffer({ resolveWithObject: true });
    let solid = 0;
    let translucent = 0;
    for (let i = 0; i < data.length; i += info.channels) {
      const alpha = data[i + 3];
      if (alpha === 255) solid += 1;
      // A band, not a value: the SVG rasteriser does not hand back exactly 127 or 128 for a
      // half-alpha stroke, and pinning one of them would be pinning sharp's rounding. The
      // `undefined` arm is `noUncheckedIndexedAccess` being narrowed explicitly rather than
      // suppressed (tsconfig.json), not a case the buffer can actually produce.
      else if (alpha !== undefined && alpha >= 110 && alpha <= 145) translucent += 1;
    }
    expect(solid).toBeGreaterThan(2000);
    expect(translucent).toBeGreaterThan(2000);
  });
});
